# Generated by Django 4.2.5 on 2023-10-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dosha_recomendado', models.CharField(max_length=30)),
                ('descripción', models.TextField()),
            ],
        ),
    ]
