# Generated by Django 4.2.5 on 2023-10-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_libro_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
